### PR TITLE
Initial support for focus reporting

### PR DESCRIPTION
**Pull request by systemmonkey42**
Added support for ANSI Focus reporting.  Included feature checkbox to disable feature reporting capability of needed.

### CODE REVIEW

**Comment by systemmonkey42** [comment]
An easy way to test this is to run from bash

```printf "\e[?1004h"; cat -v```

This should produce an initial ```^[[I``` followed by an ```^[[O``` every time the window loses focus, and another ```^[[I``` each time the window regains focus.

Disable with```printf "\e[?1004l"```

My "vim" is configured to autosave all files when losing focus, and this now works in Kitty!

Cheers.

**Comment by lars18th** [comment]
Hi @systemmonkey42 ,

I feel your patch makes the focus reporting enabled by default, and it provides an option to disable it. However, perhaps it's preferable to do it in reverse: off by default, and enable it in option. The cause is to maintain the KiTTY in line with PuTTY as most as we can.

What you think @cyd01 ?

**Comment by systemmonkey42** [comment]
Hi @cyd01 

Thanks for merging.  Tested ok in 0.73.2.7

Regards

**Comment by zdm** [comment]
How to disable this feature in config?
Kitty beeps every time.

**Comment by cyd01** [comment]
Ok, I've made a new beta build:
- focus reporting is disable by default
- it can be enable with a checkbox in Terminal/features configuration panel

You can test it [here](www.9bis.net/kitty/files/kitty-debug.exe).
Tell me if it is ok.

**Comment by zdm** [comment]
I need exe to make test.

**Comment by lars18th** [comment]
> * focus reporting is disable by default
> * it can be enable with a checkbox in Terminal/features configuration panel

I prefer this solution over enable it by default.

**Comment by systemmonkey42** [comment]
> * focus reporting is disable by default

@lars18th I admit, I wasnt happy with this at first, but with it enabled, a program in a remote shell can silently begin monitoring the activity and behaviour of kitty on your PC...  definitely warming up to the idea from a security and privacy perspective.

> Kitty beeps every time.

@zdm Can you provide instructions on how to reproduce "Kitty beeps every time."?  I'm happy to have a look at it. As a side note, I noticed on one machine (Ubuntu 14.04) focus reporting activated immediately (without requiring the activation escape sequence) and started emitting `^[[I` and `^[[O` characters which clicking in/out of the window.  However I couldn't reproduce it, which makes me thing the "enabled" state might not be initialised correctly.

**Comment by zdm** [comment]
Hi.
I don't have any special instructions.
Just run kitty and it will beep on each get or loose focus.

**Comment by systemmonkey42** [comment]
I think I've found it.
```
#ifdef MOD_PERSO
	term->no_focus_rep = true;
	term->report_focus = false;
#endif
```
is needed in term_init()  to make sure focus reporting is disabled until the control codes are received.

Let me know if you need a pull request for this.
> https://github.com/systemmonkey42/KiTTY/commits/focus_reporting_fix

**Comment by lars18th** [comment]
> Let me know if you need a pull request for this.
> 
> > https://github.com/systemmonkey42/KiTTY/commits/focus_reporting_fix

Please, @systemmonkey42 do it. This will help to @cyd01 .

**Pull request merged**
